# -*- coding: utf-8 -*-
"""114-2DSCP_Project_Exam-aware Study Planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bJpCrFHJnHG9g8AccJSwlk6cSnkvwtL
"""

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

from google.colab import files

uploaded = files.upload()

!pip install xlrd

import pandas as pd
import matplotlib.pyplot as plt
import re
from datetime import datetime, timedelta

course_data = pd.read_excel("export.xls")

course_data.head()

course_data.columns

courses = course_data[[
    "開課序號",
    "開課代碼",
    "中文課程名稱",
    "英文課程名稱",
    "學分",
    "必/選",
    "教師",
    "地點時間",
    "限修人數",
    "選修人數"
]].copy()

courses.head()

courses = courses.dropna(subset=["中文課程名稱", "地點時間"])

courses.head()

day_map = {
    "一": "Monday",
    "二": "Tuesday",
    "三": "Wednesday",
    "四": "Thursday",
    "五": "Friday",
    "六": "Saturday",
    "日": "Sunday"
}

period_order = {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "10": 10,
    "A": 11,
    "B": 12,
    "C": 13,
    "D": 14
}

def parse_class_time(text):
    text = str(text)
    pattern = r"([一二三四五六日])\s+([0-9A-D]+)-([0-9A-D]+)"
    match = re.search(pattern, text)

    if match:
        day = match.group(1)
        start_period = match.group(2)
        end_period = match.group(3)

        return pd.Series([
            day_map.get(day),
            start_period,
            end_period,
            period_order.get(start_period),
            period_order.get(end_period)
        ])

    return pd.Series([None, None, None, None, None])

courses[["day", "start_period", "end_period", "start_order", "end_order"]] = courses["地點時間"].apply(parse_class_time)

courses.head()

courses_clean = courses.dropna(subset=["day", "start_order", "end_order"]).copy()

courses_clean.head()

courses_by_day = courses_clean.groupby("day")["中文課程名稱"].count().reset_index()

courses_by_day.columns = ["day", "number_of_courses"]

courses_by_day

plt.figure(figsize=(8, 5))
plt.bar(courses_by_day["day"], courses_by_day["number_of_courses"])
plt.xlabel("Day")
plt.ylabel("Number of Courses")
plt.title("Number of Courses by Day")
plt.xticks(rotation=45)
plt.show()

required_summary = courses_clean.groupby("必/選")["中文課程名稱"].count().reset_index()

required_summary.columns = ["course_type", "number_of_courses"]

required_summary

plt.figure(figsize=(6, 5))
plt.bar(required_summary["course_type"], required_summary["number_of_courses"])
plt.xlabel("Course Type")
plt.ylabel("Number of Courses")
plt.title("Required and Elective Courses")
plt.show()

courses_clean["選修人數"] = pd.to_numeric(courses_clean["選修人數"], errors="coerce")

popular_courses = courses_clean.sort_values(by="選修人數", ascending=False)

popular_courses[[
    "中文課程名稱",
    "英文課程名稱",
    "教師",
    "地點時間",
    "選修人數"
]].head(10)

selected_course_codes = [
    "GEU0136",
    "GEU0167",
    "GEU0057"
]

my_courses = courses_clean[courses_clean["開課代碼"].isin(selected_course_codes)].copy()

my_courses[[
    "開課代碼",
    "中文課程名稱",
    "教師",
    "地點時間",
    "day",
    "start_period",
    "end_period"
]]

conflicts = []

for i in range(len(my_courses)):
    for j in range(i + 1, len(my_courses)):
        course1 = my_courses.iloc[i]
        course2 = my_courses.iloc[j]

        same_day = course1["day"] == course2["day"]
        overlap = course1["start_order"] <= course2["end_order"] and course2["start_order"] <= course1["end_order"]

        if same_day and overlap:
            conflicts.append({
                "course_1": course1["中文課程名稱"],
                "course_2": course2["中文課程名稱"],
                "day": course1["day"],
                "time_1": course1["地點時間"],
                "time_2": course2["地點時間"]
            })

conflict_table = pd.DataFrame(conflicts)

conflict_table

exams = pd.DataFrame({
    "subject": ["氣候學", "計量地理", "都市地理"],
    "exam_date": ["2026-06-10", "2026-06-13", "2026-06-17"],
    "importance": [5, 4, 3]
})

exams["exam_date"] = pd.to_datetime(exams["exam_date"])

exams

study_plan = []

for index, row in exams.iterrows():
    subject = row["subject"]
    exam_date = row["exam_date"]
    importance = row["importance"]

    for i in range(7, 0, -1):
        study_date = exam_date - timedelta(days=i)
        study_plan.append({
            "date": study_date,
            "task": "Review " + subject,
            "type": "Exam Review",
            "subject": subject,
            "hours": 1,
            "importance": importance
        })

study_plan = pd.DataFrame(study_plan)

study_plan

daily_study_hours = study_plan.groupby("date")["hours"].sum().reset_index()

daily_study_hours["status"] = daily_study_hours["hours"].apply(lambda x: "Overloaded" if x > 2 else "OK")

daily_study_hours

plt.figure(figsize=(12, 5))
plt.bar(daily_study_hours["date"].dt.strftime("%Y-%m-%d"), daily_study_hours["hours"])
plt.xlabel("Date")
plt.ylabel("Planned Study Hours")
plt.title("Daily Planned Study Hours")
plt.xticks(rotation=45)
plt.show()

study_plan_output = study_plan.copy()

study_plan_output["date"] = study_plan_output["date"].dt.strftime("%Y-%m-%d")

study_plan_output.to_csv("study_plan_output.csv", index=False)

study_plan_output

"""## Select Your Courses and Input Exam Dates

First, let's see the available courses to help you make your selection. You can copy the `開課代碼` for the courses you wish to include.
"""

print("Available courses for selection:")
display(courses_clean[["開課代碼", "中文課程名稱", "教師", "地點時間"]])

"""Next, please enter the `開課代碼` of the courses you want to select, separated by commas. For example: `GEU0136,GEU0167,GEU0057`"""

selected_course_codes_input = input("Enter course codes (comma-separated): ")
selected_course_codes = [code.strip() for code in selected_course_codes_input.split(',') if code.strip()]

my_courses = courses_clean[courses_clean["開課代碼"].isin(selected_course_codes)].copy()

print("Your selected courses:")
display(my_courses[["開課代碼", "中文課程名稱", "教師", "地點時間", "day", "start_period", "end_period"]])

"""Now, for each of your selected courses, please manually input the exam date and its importance (e.g., a number from 1 to 5, where 5 is most important).

Edit the `exam_data_list` below with the correct information. The 'subject' should match the `中文課程名稱` from your selected courses.
"""

# 1. 請在此處手動輸入您的考試日期與重要程度
# 格式範例：{"subject": "氣候學", "exam_date": "2026-06-10", "importance": 5}
exam_data_list = [
    # 如果自動生成的列表不正確，您可以在這裡手動添加或修改
]

# 自動從您選修的課程中預填，方便您編輯
for _, row in my_courses.iterrows():
    if not any(d['subject'] == row['中文課程名稱'] for d in exam_data_list):
        exam_data_list.append({
            "subject": row["中文課程名稱"],
            "exam_date": "2026-06-20", # <--- 請將這裡改為實際日期 (YYYY-MM-DD)
            "importance": 3            # <--- 請按需求修改重要程度 (1-5)
        })

# 轉換為 DataFrame
exams = pd.DataFrame(exam_data_list)

# 檢查是否有尚未修改的預設文字，避免轉換錯誤
if (exams['exam_date'] == "YYYY-MM-DD").any():
    print("⚠️ 提示：請先將上面的 'YYYY-MM-DD' 替換為實際的日期格式（如 '2026-06-20'）再執行。")
else:
    exams["exam_date"] = pd.to_datetime(exams["exam_date"])
    print("您的考試日程表：")
    display(exams)

"""### 互動式課程與考試設定
請使用下方的介面選擇課程並設定考試資訊。
"""

import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd

# 儲存選擇的考試資料
if 'final_exam_list' not in locals():
    final_exam_list = []

# 建立選單元件
course_options = sorted(courses_clean['中文課程名稱'].unique().tolist())
course_dropdown = widgets.Dropdown(options=course_options, description='選擇課程:', style={'description_width': 'initial'})
exam_name_input = widgets.Text(value=course_dropdown.value, description='考試名稱:', style={'description_width': 'initial'})
date_picker = widgets.DatePicker(description='考試日期:', style={'description_width': 'initial'})
importance_slider = widgets.IntSlider(value=3, min=1, max=5, step=1, description='重要程度:', style={'description_width': 'initial'})
add_button = widgets.Button(description="新增至清單", button_style='success')
output = widgets.Output()

# 當課程更換時，自動同步考試名稱
def on_course_change(change):
    exam_name_input.value = change['new']
course_dropdown.observe(on_course_change, names='value')

# 按鈕點擊事件
def add_exam(b):
    with output:
        if date_picker.value is None:
            print("❌ 請先選擇日期！")
            return

        new_entry = {
            "subject": exam_name_input.value,
            "exam_date": date_picker.value.strftime('%Y-%m-%d'),
            "importance": importance_slider.value
        }
        final_exam_list.append(new_entry)
        clear_output()
        print(f"✅ 已新增：{new_entry['subject']} ({new_entry['exam_date']})")
        display(pd.DataFrame(final_exam_list))

add_button.on_click(add_exam)

# 顯示介面
ui = widgets.VBox([course_dropdown, exam_name_input, date_picker, importance_slider, add_button, output])
display(ui)

"""確認新增完所有考試後，執行下方儲存格來更新 `exams` 資料表。"""

if 'final_exam_list' in locals() and final_exam_list:
    exams = pd.DataFrame(final_exam_list)
    exams['exam_date'] = pd.to_datetime(exams['exam_date'])
    print("最終確認的考試日程表：")
    display(exams)
else:
    print("清單目前是空的，請先在上方介面新增考試。")

"""### 整合課表與複習計畫 (Timetable Style)
此區塊將自動計算空檔時段，並填入複習任務。
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 1. 定義時間段 (08:00 - 22:00)
time_slots = [f"{h:02d}:00" for h in range(8, 22)]
days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

# 2. 獲取本週日期範圍 (以今天開始的 7 天為例)
today = datetime.now().date()
date_range = [today + timedelta(days=i) for i in range(7)]

# 初始化課表數據矩陣
schedule_df = pd.DataFrame(index=time_slots, columns=[d.strftime('%Y-%m-%d (%a)') for d in date_range])
schedule_df.fillna("---(空閒)---", inplace=True)

# 3. 標記正課時段 (避開時段)
for _, row in my_courses.iterrows():
    day_name = row['day']
    start_h = row['start_order'] + 7 # 假設節次 1 是 08:00
    end_h = row['end_order'] + 7

    for dt in date_range:
        if dt.strftime('%A') == day_name:
            col = dt.strftime('%Y-%m-%d (%a)')
            for h in range(start_h, end_h + 1):
                slot = f"{h:02d}:00"
                if slot in schedule_df.index:
                    schedule_df.at[slot, col] = f"🚫 正課: {row['中文課程名稱']}"

# 4. 安排複習進度 (根據距離與重要度)
if not exams.empty:
    # 計算權重：(重要度 * 5) / (距離天數 + 1)
    exam_task_pool = []
    for _, ex in exams.iterrows():
        days_left = (ex['exam_date'].date() - today).days
        if days_left >= 0:
            # 依照權重決定複習總時數 (簡單公式：重要度 * 2)
            hours_needed = int(ex['importance'] * 2)
            exam_task_pool.extend([ex['subject']] * hours_needed)

    # 將複習任務填入空閒時段
    task_idx = 0
    for col in schedule_df.columns:
        for slot in schedule_df.index:
            if schedule_df.at[slot, col] == "---(空閒)---" and task_idx < len(exam_task_pool):
                schedule_df.at[slot, col] = f"📖 複習: {exam_task_pool[task_idx]}"
                task_idx += 1

# 5. 呈現圖表資訊
print("📅 未來 7 天整合課表與複習計畫：")
display(schedule_df.style.set_properties(**{
    'text-align': 'center',
    'border': '1px solid black',
    'background-color': '#f9f9f9'
}))

!apt-get -y install fonts-wqy-zenhei

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 設定中文字體
font_path = '/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc'
fe = fm.FontEntry(fname=font_path, name='WQY-ZenHei')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = fe.name
plt.rcParams['axes.unicode_minus'] = False

# 統計複習佔比
task_counts = []
for col in schedule_df.columns:
    counts = schedule_df[col].value_counts()
    for task, count in counts.items():
        if "複習" in task:
            task_counts.append({"日期": col, "科目": task.replace("📖 複習: ", ""), "小時": count})

if task_counts:
    viz_df = pd.DataFrame(task_counts)
    plt.figure(figsize=(12, 6))
    sns.barplot(data=viz_df, x="日期", y="小時", hue="科目")
    plt.title("每日各科複習時數分配", fontsize=16)
    plt.xlabel("日期", fontsize=12)
    plt.ylabel("累計小時", fontsize=12)
    plt.xticks(rotation=45)
    plt.legend(title="複習科目", bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()
else:
    print("目前沒有安排複習任務，請確認考試日期是否在未來 7 天內。")